Team6/Team6/Models/Criminal.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using Team6.Models;
using Team6.DAL;

namespace Team6.Models
{

    public enum State
    {
        [Description("None")]None,
        [Description("AL")]AL,
        [Description("AK")]AK,
        [Description("AZ")]AZ,
        [Description("AR")]AR,
        [Description("CA")]CA,
        [Description("CO")]CO,
        [Description("CT")]CT,
        [Description("DE")]DE,
        [Description("FL")]FL,
        [Description("GA")]GA,
        [Description("HI")]HI,
        [Description("ID")]ID,
        [Description("IL")]IL,
        [Description("IN")]IN,
        [Description("IA")]IA,
        [Description("KS")]KS,
        [Description("KY")]KY,
        [Description("LA")]LA,
        [Description("ME")]ME,
        [Description("MD")]MD,
        [Description("MA")]MA,
        [Description("MI")]MI,
        [Description("MN")]MN,
        [Description("MS")]MS,
        [Description("MO")]MO,
        [Description("MT")]MT,
        [Description("NE")]NE,
        [Description("NV")]NV,
        [Description("NH")]NH,
        [Description("NJ")]NJ,
        [Description("NM")]NM,
        [Description("NY")]NY,
        [Description("NC")]NC,
        [Description("ND")]ND,
        [Description("OH")]OH,
        [Description("OK")]OK,
        [Description("OR")]OR,
        [Description("PA")]PA,
        [Description("RI")]RI,
        [Description("SC")]SC,
        [Description("SD")]SD,
        [Description("TN")]TN,
        [Description("TX")]TX,
        [Description("UT")]UT,
        [Description("VT")]VT,
        [Description("VA")]VA,
        [Description("WA")]WA,
        [Description("WV")]WV,
        [Description("WI")]WI,
        [Description("WY")]WY
    }

    public enum Gender
    {
        [Description("None")]
        None,
        [Description("Male")]
        Male,
        [Description("Female")]
        Female
    }

    public enum EyeColor
    {
        [Description("None")]
        None,
        [Description("Amber")]
        Amber,
        [Description("Blue")]
        Blue,
        [Description("Brown")]
        Brown,
        [Description("Black")]
        Black,
        [Description("Grey")]
        Gray,
        [Description("Green")]
        Green,
        [Description("Hazel")]
        Hazel
    }

    public enum HairColor
    {
        [Description("None")]
        None,
        [Description("Black")]
        Black,
        [Description("Brown")]
        Brown,
        [Description("Red")]
        Red,
        [Description("Blonde")]
        Blonde,
        [Description("Grey")]
        Grey,
        [Description("White")]
        White,
        [Description("Bald")]
        Bald,
        [Description("Other")]  
        Other
    }

    public enum Race
    {
        [Description("None")] None,
        [Description("American Indian / Alaska Native")] AmericanIndianAlaskaNative,
        [Description("Asian")] Asian,
	    [Description("Black / African American")] BlackAfricanAmerican,
        [Description("Hispanic")] Hispanic,
	    [Description("Native Hawaiian / Pacific Islander")] NativeHawaiianPacificIslander,
        [Description("White")] White,
    }

    public class Criminal
    {
        [Display(Name = "Criminal ID")]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int CriminalID { get; set; }

        [StringLength(30)]
        [Display(Name = "First Name")]
        [RegularExpression("^([a-zA-Z '-]+)$", ErrorMessage = "Invalid First Name")]
        [Required(ErrorMessage = "First Name is required")]
        public string FirstName { get; set; }


        [StringLength(30)]
        [Display(Name = "Last Name")]
        [RegularExpression("^([a-zA-Z '-]+)$", ErrorMessage = "Invalid Last Name")]
        [Required(ErrorMessage = "Last Name is required")]
        public string LastName { get; set; }

        [Display(Name = "Eye Color")]
        public EyeColor? EyeColor { get; set; }

        [Display(Name = "Weight")]
        [Required(ErrorMessage = "Weight is required")]
        public int Weight { get; set; }

        [Display(Name = "Height")]
        [Required(ErrorMessage = "Height is required")]
        public int Height { get; set; }


        [Display(Name = "Gender")]
        public Gender? Gender { get; set; }

        [Display(Name = "Social Security Number")]
        [RegularExpression("^([0-9]+)$", ErrorMessage = "Invalid Social Security Number")]
        [Range(111111111, 999999999, ErrorMessage = "SSN size invalid")]
        [Required(ErrorMessage = "Social Security Number is required")]
        public int Ssn { get; set; }

        [Display(Name = "Alias")]
        public string Alias { get; set; }

        [Display(Name = "Hair Color")]
        public HairColor? HairColor { get; set; }

        [Display(Name = "Known Affiliates")]
        public string KnownAffiliates { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Date Of Birth")]
        [Required(ErrorMessage = "Date of Birth is required")]
        public DateTime DateOfBirth { get; set; }

        [Display(Name = "Race")]
        public Race? Race { get; set; }

        [StringLength(60)]
        [Display(Name = "Address")]
        public string Address { get; set; }

        [Display(Name = "Zip Code")]
        public int ZipCode { get; set; }

        [Display(Name = "City")]
        public string City { get; set; }

        [Display(Name = "State")]
        public State? State { get; set; }

        [Display(Name = "Phone Number")]
        public Int64 PhoneNumber { get; set; }

        [Display(Name = "Miscellaneous")]
        public string misc { get; set; }

        [Display(Name = "Mug Shot")]
        public string image { get; set; }


        //public virtual CrimeReport CrimeReport { get; set; }
        public virtual ICollection<CrimeReport> CrimeReports { get; set; }

        public int getHighestID()
        {
            Team6Context dre = new Team6Context();
            var user = from o in dre.Criminals select o.CriminalID;
            return user.Max();

        }
    }
}

Team6/Team6/Controllers/CriminalController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Team6.Models;
using Team6.DAL;
using System.IO;
using System.Web.Helpers;
namespace Team6.Controllers
{
    public class CriminalController : Controller
    {
        private Team6Context db = new Team6Context();
        //FileStream fs = new FileStream("C:/Users/Muhammad Naviwala/Documents/GitHub/criminal_queries.log", FileMode.OpenOrCreate);

        // GET: /Criminal/
        public ActionResult Index()
        {
            if (!(System.Web.HttpContext.Current.User != null && System.Web.HttpContext.Current.User.Identity.IsAuthenticated))
            {
                return RedirectToAction("LogOn", "Home");
            }
            return View(db.Criminals.OrderBy(x => x.FirstName).ThenBy(x => x.LastName).ToList());
        }

        // GET: /Criminal/Details/5
        public ActionResult Details(int? id)
        {
            if (!(System.Web.HttpContext.Current.User != null && System.Web.HttpContext.Current.User.Identity.IsAuthenticated))
            {
                return RedirectToAction("LogOn", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Criminal criminal = db.Criminals.Find(id);
            if (criminal == null)
            {
                return HttpNotFound();
            }
            return View(criminal);
        }

        // GET: /Criminal/Create
        public ActionResult Create()
        {
            if (!(System.Web.HttpContext.Current.User != null && System.Web.HttpContext.Current.User.Identity.IsAuthenticated))
            {
                return RedirectToAction("LogOn", "Home");
            }
            return View();
        }
        

        // POST: /Criminal/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CriminalID,FirstName,LastName,EyeColor,Weight,Height,Gender,Ssn,Alias,HairColor,KnownAffiliates,DateOfBirth,Race,Address,City,State,ZipCode,PhoneNumber,misc,Photo")] Criminal criminal, FormCollection formCollection, HttpPostedFileBase file)
        {
            if (!(System.Web.HttpContext.Current.User != null && System.Web.HttpContext.Current.User.Identity.IsAuthenticated))
            {
                return RedirectToAction("LogOn", "Home");
            }
            if (file != null && file.ContentLength > 0)
            {
                var fileName = string.Format(@"{0}.txt", Guid.NewGuid()) + Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Photos"), fileName);
                file.SaveAs(path);
                criminal.image = "~/Photos/" + fileName;
            }
            else
            {
                criminal.image="~/Photos/unknown.jpg";
            }

            criminal.CriminalID = criminal.getHighestID() + 1;

            criminal.Height = Convert.ToInt32(formCollection["HeightFeet"]) * 12 + Convert.ToInt32(formCollection["HeightInches"]);
            if (ModelState.IsValid)
            {
                db.Criminals.Add(criminal);
                try{
                db.SaveChanges();
                }
                catch (Exception)
                {

                    ModelState.AddModelError("", "invalid information");
                    return View(criminal);
                }
                return RedirectToAction("Index");
            }

            return View(criminal);
        }

        // GET: /Criminal/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!(System.Web.HttpContext.Current.User != null && System.Web.HttpContext.Current.User.Identity.IsAuthenticated))
            {
                return RedirectToAction("LogOn", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Criminal criminal = db.Criminals.Find(id);
            if (criminal == null)
            {
                return HttpNotFound();
            }
            return View(criminal);
        }

        // POST: /Criminal/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CriminalID,FirstName,LastName,EyeColor,Weight,Height,Gender,Ssn,Alias,HairColor,KnownAffiliates,DateOfBirth,Race,Address,City,State,ZipCode,PhoneNumber,misc,Image")] Criminal criminal, FormCollection formCollection, HttpPostedFileBase file)
        {
            if (!(System.Web.HttpContext.Current.User != null && System.Web.HttpContext.Current.User.Identity.IsAuthenticated))
            {
                return RedirectToAction("LogOn", "Home");
            }
                if (file != null && file.ContentLength > 0)
                {
                    var fileName = string.Format(@"{0}.txt", Guid.NewGuid()) + Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Photos"), fileName);
                    file.SaveAs(path);
                    criminal.image = "~/Photos/" + fileName;
                }
                else if (criminal.image != "~/Photos/unknown.jpg" && criminal.image != null)
                {
                    criminal.image = criminal.image;
                }
                else
                {
                    criminal.image = "~/Photos/unknown.jpg";
                }
            string Heightvalue = formCollection["HeightFeet"];
            string Heightvalue2 = formCollection["HeightInches"];

            criminal.Height = Convert.ToInt32(Heightvalue) * 12 + Convert.ToInt32(Heightvalue2);
            if (ModelState.IsValid)
            {
                db.Entry(criminal).State = EntityState.Modified;
                try{
                db.SaveChanges();
                }
                catch (Exception)
                {

                    ModelState.AddModelError("", "invalid information");
                    return View(criminal);
                }
                return RedirectToAction("Index");
            }
            return View(criminal);
        }

        // GET: /Criminal/Delete/5
        public ActionResult Delete(int? id)
        {
            if (!(System.Web.HttpContext.Current.User != null && System.Web.HttpContext.Current.User.Identity.IsAuthenticated))
            {
                return RedirectToAction("LogOn", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Criminal criminal = db.Criminals.Find(id);
            if (criminal == null)
            {
                return HttpNotFound();
            }
            return View(criminal);
        }

        // POST: /Criminal/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!(System.Web.HttpContext.Current.User != null && System.Web.HttpContext.Current.User.Identity.IsAuthenticated))
            {
                return RedirectToAction("LogOn", "Home");
            }
            Criminal criminal = db.Criminals.Find(id);
            db.Criminals.Remove(criminal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult SearchCriminal(string firstName, string lastName, string weight, string height, string ssn, string address, string zipCode, Race race, State state, Gender gender, EyeColor eyeColor, HairColor hairColor)
        {
            if (!(System.Web.HttpContext.Current.User != null && System.Web.HttpContext.Current.User.Identity.IsAuthenticated))
            {
                return RedirectToAction("LogOn", "Home");
            }
            var context = new Team6Context();
            string sqlQuery = "SELECT * FROM dbo.Criminal";
            bool cont = false;

            if (string.IsNullOrEmpty(firstName) && string.IsNullOrEmpty(lastName) && string.IsNullOrEmpty(weight) && string.IsNullOrEmpty(height) && string.IsNullOrEmpty(ssn) && string.IsNullOrEmpty(address) && string.IsNullOrEmpty(zipCode) && race.Equals(Race.None) && state.Equals(State.None) && gender.Equals(Gender.None) && eyeColor.Equals(EyeColor.None) && hairColor.Equals(HairColor.None))
            {
                // some error message that the user should enter at least one field
            }
            else
            {
                sqlQuery = "SELECT * FROM dbo.Criminal WHERE ";

                if (!string.IsNullOrEmpty(firstName))
                {
                    if (cont)
                        sqlQuery += " AND ";
                    firstName = firstName.Replace("'", "''");
                    sqlQuery += "FirstName LIKE \'%" + firstName + "%\'";
                    cont = true;
                }

                if (!string.IsNullOrEmpty(lastName))
                {
                    if (cont)
                        sqlQuery += " AND ";
                    lastName = lastName.Replace("'", "''");
                    sqlQuery += "LastName LIKE \'%" + lastName + "%\'";
                    cont = true;
                }

                if (!string.IsNullOrEmpty(weight))
                {

Team6/Team6/Views/Criminal/Create.cshtml
@using Team6.helpers.enumhelper
@using Team6.Models
@using Microsoft.Web
@model Team6.Models.Criminal

@{
    ViewBag.Title = "Create new criminal";
}

<h2>Create new criminal</h2>
<hr />


@using (Html.BeginForm("Create" ,"Criminal", FormMethod.Post, new { EncType = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true)

        <div class="form-group">
            <label class="col-sm-2 control-label">@Html.LabelFor(model => model.FirstName)</label>
            <div class="col-sm-4">
                @Html.EditorFor(model => model.FirstName)
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>

            <label class="col-sm-2 control-label">@Html.LabelFor(model => model.LastName)</label>
            <div class="col-sm-4">
                @Html.EditorFor(model => model.LastName)
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">@Html.LabelFor(model => model.Height)</label>
            <div class="col-sm-4">
                @using (Html.BeginForm("NewHeight", "Admin"))
                {
                    <select id="HeightFeet" name="HeightFeet">
                        <option>0</option>
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                        <option>6</option>
                        <option>7</option>
                        <option>8</option>
                        <option>9</option>
                        <option>10</option>
                        <option>11</option>
                        <option>12</option>
                    </select>
                    <select id="HeightInches" name="HeightInches">
                        <option>0</option>
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                        <option>6</option>
                        <option>7</option>
                        <option>8</option>
                        <option>9</option>
                        <option>10</option>
                        <option>11</option>
                    </select>
                }
                @Html.ValidationMessageFor(model => model.Height)
            </div>

            <label class="col-sm-2 control-label">@Html.LabelFor(model => model.Weight)</label>
            <div class="col-sm-4">
                @Html.EditorFor(model => model.Weight)
                @Html.ValidationMessageFor(model => model.Weight)
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">@Html.LabelFor(model => model.EyeColor)</label>
            <div class="col-sm-4">
                @Html.DropDownListFor(model => model.EyeColor, enumHelper.GetSelectedItemList<EyeColor>(), new { style = "width:160px" })
                @Html.ValidationMessageFor(model => model.EyeColor)
            </div>

            <label class="col-sm-2 control-label">@Html.LabelFor(model => model.Gender)</label>
            <div class="col-sm-4">
                @Html.DropDownListFor(model => model.Gender, enumHelper.GetSelectedItemList<Gender>(), new { style = "width:160px" })
                @Html.ValidationMessageFor(model => model.Gender)
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">@Html.LabelFor(model => model.Ssn)</label>
            <div class="col-sm-4">
                @Html.EditorFor(model => model.Ssn)
                @Html.ValidationMessageFor(model => model.Ssn)
            </div>

            <label class="col-sm-2 control-label">@Html.LabelFor(model => model.Alias)</label>
            <div class="col-sm-4">
                @Html.EditorFor(model => model.Alias)
                @Html.ValidationMessageFor(model => model.Alias)
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">@Html.LabelFor(model => model.HairColor)</label>
            <div class="col-sm-4">
                @Html.DropDownListFor(model => model.HairColor, enumHelper.GetSelectedItemList<HairColor>(), new { style = "width:160px" })
                @Html.ValidationMessageFor(model => model.HairColor)
            </div>

            <label class="col-sm-2 control-label">@Html.LabelFor(model => model.KnownAffiliates)</label>
            <div class="col-sm-4">
                @Html.EditorFor(model => model.KnownAffiliates)
                @Html.ValidationMessageFor(model => model.KnownAffiliates)
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">@Html.LabelFor(model => model.DateOfBirth)</label>
            <div class="col-sm-4">
                @Html.EditorFor(model => model.DateOfBirth)
                @Html.ValidationMessageFor(model => model.DateOfBirth)
            </div>

            <label class="col-sm-2 control-label">@Html.LabelFor(model => model.Race)</label>
            <div class="col-sm-4">
                @Html.DropDownListFor(model => model.Race, enumHelper.GetSelectedItemList<Race>(), new { style = "width:160px" })
                @Html.ValidationMessageFor(model => model.Race)
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">@Html.LabelFor(model => model.Address)</label>
            <div class="col-sm-4">
                @Html.EditorFor(model => model.Address)
                @Html.ValidationMessageFor(model => model.Address)
            </div>

            <label class="col-sm-2 control-label">@Html.LabelFor(model => model.City)</label>
            <div class="col-sm-4">                
                @Html.EditorFor(model => model.City)
                @Html.ValidationMessageFor(model => model.City)
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">@Html.LabelFor(model => model.State)</label>
            <div class="col-sm-4">
                @Html.DropDownListFor(model => model.State, enumHelper.GetSelectedItemList<State>(), new { style = "width:160px" })
                @Html.ValidationMessageFor(model => model.State)
            </div>

            <label class="col-sm-2 control-label">@Html.LabelFor(model => model.ZipCode)</label>
            <div class="col-sm-4">
                @Html.EditorFor(model => model.ZipCode)
                @Html.ValidationMessageFor(model => model.ZipCode)
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">@Html.LabelFor(model => model.PhoneNumber)</label>
            <div class="col-sm-4">
                @Html.EditorFor(model => model.PhoneNumber)
                @Html.ValidationMessageFor(model => model.PhoneNumber)
            </div>

            <label class="col-sm-2 control-label">@Html.LabelFor(model => model.misc)</label>
            <div class="col-sm-4">
                @Html.EditorFor(model => model.misc)
                @Html.ValidationMessageFor(model => model.misc)
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">@Html.LabelFor(model => model.image)</label>
            <div class="col-sm-10">
                

                    <label for="file">Please choose an Image:</label>
                    <input type="file" name="file" id="file" />

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-10 col-md-10">
                <input type="submit" class="btn btn-default">
            </div>
        </div>

    </div>
}

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>

            @section Scripts {
                @Scripts.Render("~/bundles/jqueryval")
            }

Team6/Team6/Views/Criminal/CriminalReportSheet.cshtml
@model IEnumerable<Team6.Models.Criminal>

@{
    ViewBag.Title = "CriminalReport";
}

<center><h2>Criminal Report Sheet</h2></center>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EyeColor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Weight)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Height)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ssn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Alias)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HairColor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KnownAffiliates)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Race)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ZipCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.misc)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        HttpCookie cookie = Request.Cookies[FormsAuthentication.FormsCookieName];
        FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(cookie.Value);
        if (item.DateOfBirth.AddYears(18) < DateTime.Now)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EyeColor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Weight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Height)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ssn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Alias)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HairColor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KnownAffiliates)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfBirth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Race)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.State)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ZipCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.misc)
                </td>
            </tr>
        }
        else
            if (ticket.UserData == "ChiefOfPolice" || ticket.UserData == "AssistantChief")
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EyeColor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Weight)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Height)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Gender)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ssn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Alias)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HairColor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.KnownAffiliates)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateOfBirth)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Race)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.State)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ZipCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PhoneNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.misc)
                    </td>
                </tr>
            }
    }

</table>